### ISSUE TITLE
Apple ASCII art not updating in "Bright" mode

### ISSUE THREAD

**Issue by dannyneira** [trbnhck/warp-theme#9]
**Describe the bug**
The Apple in the theme build preview doesn't update colors when the Terminal Colors is toggled to "Bright" mode.

**To Reproduce**
1. Go to Page https://warp-theme.vercel.app/#
2. Toggle Terminal Colors to 'Bright'
3. Change some colors
4. See error in Apple ascii preview not updating

**Expected behavior**
The Apple preview should update the colors like in "Normal" Terminal Colors mode.

**Screenshots**
(https://www.loom.com/share/12e13e1b5062458bb5cd053114c17b3b)

**Desktop (please complete the following information):**
 - OS: MacOS 12.5
 - Browser: Chrome
 - Version: 104.0.5112.79 (Official Build) (x86_64)

**Additional context**
Brilliant work on this theme builder, looking forward to Warp users delight to use it!

**Comment by trbnhck** [comment]
Thank you for creating the issue :)

This shouldn’t be a bug, in my understanding, since the Apple ASCII art uses the normal color variations and therefore isn’t affected by changes to the bright variations 🤔

If I‘m missing something here please let me know :)

**Comment by dannyneira** [comment]
I see that now, thanks for clarifying. Cheers!
